### ISSUE TITLE
What are the supported sizes?

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-media-recoder#2]
@thepiwo Which formats will be accepted and to which sizes will transformations happen? Asking this for @tinobo and @leokaessner. Will add to documentation / Readme

**Comment by thepiwo** [comment]
I'll write some documentation here soon:
https://github.com/BreakOutEvent/breakout-media-recoder/wiki

**Comment by thepiwo** [comment]
I've written some documentation. For our special configuration i'll have a discussion with the app and frontend people
